### ISSUE TITLE
Call the function from a method

### ISSUE THREAD

**Issue by jsd219** [vuejs-community/vue-filter-date-parse#226]
Great plugin! Is there a way to call the filter from a method?

**Comment by eduardnikolenko** [comment]
Hi.
You can two ways for use dateFormat as a function, by example:

```vue
<template>
  <div>{{ filteredDateValue }}</div>
</template>

<script>
  const value = new Date();
  const format = 'YYYY-MM-DD';
  const options = {};

  export default {
    computed: {
      filteredDateValue() {
        return this.$options.filters.dateFormat(value, format, options /* options optional */);
      }
    }
  };
</script>
```
or
```vue
<template>
  <div>{{ filteredDateValue }}</div>
</template>

<script>
  import { dateFormat } from '@vuejs-community/vue-filter-date-format';

  const value = new Date();
  const format = 'YYYY-MM-DD';
  const options = {};

  export default {
    computed: {
      filteredDateValue() {
        return dateFormat(value, format, options /* options optional */);
      }
    }
  };
</script>
```

**Comment by jsd219** [comment]
Hi,

I thought so too but when I run this:

this.users.filter((item) => {
    console.log(this.$options.filters.dateFormat(item.joined, 'MMM. DD, YYYY'))
} )

I get an error: "Error in v-on handler: "TypeError: input.getFullYear is not a function”"


God Bless

Jason Demetri
Owner | Rayrok
e ***@***.*** ***@***.***> | m 512.289.4333 <tel:512.289.4333>

"What better to get wisdom than gold, to choose understanding rather than silver"
Proverbs 16:16

**Comment by jsd219** [comment]
I figured it out. I needed to do this 
console.log(this.$options.filters.dateFormat(new Date(item.joined), 'MMM. DD, YYYY'))

**Comment by jsd219** [comment]
Thank you for the quick response and the great filter!
