### ISSUE TITLE
Formatted date comes back with too much information

### ISSUE THREAD

**Issue by danielrvancura** [vuejs-community/vue-filter-date-parse#87]
I'm using your date parser and it works well for what I need but it returns too much information. I'm requesting: <p>{{setlist.eventDate | dateParse('DD-MM-YYYY') | dateFormat('MM-DD-YYYY')}}</p> and getting back: "Tue Feb 11 2020 00:00:00 GMT-0800 (Pacific Standard Time)." when all I want is  "Feb 11 2020." How can I drop everything from the return except the date?

**Comment by eduardnikolenko** [comment]
HI.
I cannot reproduce this case.
